### ISSUE TITLE
ice_recur fails on twice-weekly entries

### ISSUE THREAD

**Issue by JonathanReeve** [rlpowell/todo-text-stuff#1]
In the comments at the top of `ice_recur`, one of the examples is a task that runs twice weekly, on Friday and Sunday: `weekly ; day Friday, Sunday - Runs every Friday and Saturday` . But if you try this task, it doesn't work. I have an entry in recur.txt that reads: `weekly ; day Friday, Sunday - (A) go to gym @today @personal`, and it checks out ok with `todo.sh ice_recur -s`: `Schedule: weekly ; day Friday, Sunday -- Next Day: 2016-09-02 -- Text: (A) go to gym @today @personal`, but it fails with `todo.sh ice_recur`: 

```
~/.todo.actions.d/recur:242:in `<main>': Bad entries found in /home/jon/Dropbox/Personal/Todo/recur.txt:  (RuntimeError)
weekly ; day Friday, Sunday - (A) go to gym @today @personal
```

**Comment by rlpowell** [comment]
*Whoopsy*.  I was explicitely excluding entries with , in them.
Thanks for the heads up!

Fixed!
