### ISSUE TITLE
Looks at threshold dates when determining duplicates not ideal behavior

### ISSUE THREAD

**Issue by excetara2** [rlpowell/todo-text-stuff#10]
Other recur functions don't look at threshold dates when determining if it is a duplicate. I think this is the ideal behavior except that I don't know ruby to be able to fix this. Or is this ideal behavior to include threshold dates when determining if it is a duplicate?

**Comment by rlpowell** [comment]
I'm sorry, I don't understand what you're saying.  Can you give me a specific, concrete example of the program not working as you expect?

**Comment by JSpenced** [comment]
So let's say you have this for the first sunday:

first,second,third,fourth,fifth Sunday: (B) Weekly review @computer

then you add to it a threshold after it's added to todotxt:

(B) Weekly review @computer t:2018-12-01

The threshold will cause it to be re-added again next week if you haven't completed the task or removed it from the list eg...:

(B) Weekly review @computer
(B) Weekly review @computer t:2018-12-01

I just also have used ice_recur and it ignores threshold dates but not due dates (this I need to double check as don't use due dates as often) when determining to add an entry again. Anyways, this rarely happens but it happened once or twice to me so thought I would ask about if threshold dates could be ignored when adding.

**Comment by rlpowell** [comment]
In version 1.4, I dropped the todo.txt gem I was using and rolled my own; I believe this fixes this issue.  Please test.

Note that there is no general standard for the format of key/value tags, so while I'm reasonably certain this handles t: and note:, it won't handle anything else unless someone asks me to.

**Comment by JSpenced** [comment]
How do I go about to modify it (for example, I also want it to ignore priority or due date) just for future reference?

**Comment by JSpenced** [comment]
Priority is handled but not due date, fyi!? I just tried a thorough check. I think the most important ones to handle probably are priority, due date, and threshold because these can change.

Also, project and context are handled which is probably fine, but maybe project shouldn't be handled??

Theoretically, you could have the same task for two different projects.

**Comment by rlpowell** [comment]
On Sun, Dec 02, 2018 at 12:30:55AM -0800, Jeff Spencer wrote:
> Priority is handled but not due date, fyi!? I just tried a
> thorough check. I think the most important ones to handle probably
> are priority, due date, and threshold because these can change.

Can you show me the raw line for an example with due date, please?

> Also, project and context are handled which is probably fine, but
> maybe project shouldn't be handled??
> 
> Theoretically, you could have the same task for two different projects. 

I can see this one either way; if you think I should drop projects,
I can do that.  It doesn't matter to my personal workflow in either
case.

I could make it a flag, I suppose.

**Comment by JSpenced** [comment]
I would drop projects then as default (think that's the more desired behavior) and then make including it as a flag.

Here is an example:
(A) 2018-06-05 Do this due:2019-05-18 t:2019-05-04

I added this to my file to fix it as stated above:
'task = task.gsub( %r{(?:\s|^)due:[a-zA-Z0-9.-]+}, '' )'

**Comment by JSpenced** [comment]
The only other thing I've ever wanted was for it to check when the last time it was run. For example, if you had your computer off for three days. It would see that it wasn't run and run for each day it missed. Basically, it would need an external file to keep track of the last day the script was run or if the file didn't exist then just run for the current day.

Anyways this would be a new proposed feature, but when I was on holiday I needed this. Also, at least on mac, if you put it in your cron and restart your computer it will run again on that day.

**Comment by rlpowell** [comment]
> The only other thing I've ever wanted was for it to check when the last time it was run. For example, if you had your computer off for three days. It would see that it wasn't run and run for each day it missed. Basically, it would need an external file to keep track of the last day the script was run or if the file didn't exist then just run for the current day.
> 
> Anyways this would be a new proposed feature, but when I was on holiday I needed this. Also, at least on mac, if you put it in your cron and restart your computer it will run again on that day.

You're in luck!  I already did that earlier this week.  :D 

I realize, now that you mention it, that it *will* run twice on the same day.  I've fixed that, now, too; please try it out.

**Comment by rlpowell** [comment]
OK!  Try the new version please!  I think it does everything you wanted.

If not, please open a new issue; this one is getting pretty long.

**Comment by JSpenced** [comment]
Okay! Thanks and I'll give it a try over the next day and let you know of any issues.
