### ISSUE TITLE
Check for running the previous days don't run the day it was last accessed/modified

### ISSUE THREAD

**Issue by JSpenced** [rlpowell/todo-text-stuff#13]
I just did a test on this by running: 
`touch -r filelastmodifiedaccessedyesterday.txt .ice_recur_completed`
then (the file last accessed/modified date was December 2nd):
`todo.sh ice_recur`
it ran for both December 2nd and December 3rd.

Since `.ice_recur_completed` was last accessed on December 2nd, it should have already  run for December 2nd (so shouldn't have run again for this date). It should have only run for the current day (December 3rd).

I didn't look at the code but not sure how you determine last modified or last accessed but either way do you think this is wrong? Or just my testing is off?

I will look at this again more closely tomorrow. I have a lot of tasks on Sunday so it's a bit annoying to look in deeper as many tasks get added.

**Comment by rlpowell** [comment]
So as an aside, I find this more comfortable:

```
touch -d "8 days ago" ~/todo/.ice_recur_completed
touch -d yesterday ~/todo/.ice_recur_completed
```

For testing like this, you could always use -n, and then it doesn't matter how many things are going to get added.

And yeah, you're right; try the newest version please.

**Comment by JSpenced** [comment]
Yeah, you are right. When I was testing this, I hadn't figured out -n would run dry_run yet.

I think the touch command on mac doesn't have `-d` but you can use `-mt` probably the same. I just had updated a couple of files the previous two days so that was just as easy.

Anyways, everything seems to be working now and I've gotten rid of the original recur completely now so thanks!

**Comment by JSpenced** [comment]
The only other thing I can think to add that I don't actually need would be to add a command line option that would ignore checking the `.ice_recur_completed` file and run no matter what. So the output message could say delete the file or run with `-f` to force ice_recur to run.
