### ISSUE TITLE
Feature Request: Start date for script to run but no end date

### ISSUE THREAD

**Issue by JSpenced** [rlpowell/todo-text-stuff#16]
I just realized when updating the readme there is a start date with `@` that the script should start to run at. Could you make an end date for the script to stop running with `@@` or some other marker?

I think then you could start the script from when it is added or a specific start date with `@`  but then it would end in three months (or whatever the specified end date is.

**Comment by rlpowell** [comment]
So, like, "daily from 1 Jan 2018 to 2 Feb 2018", sort of thing?

**Comment by JSpenced** [comment]
Yes, exactly.

`daily from 1 Jan 2018 to 2 Feb 2018` or `daily to 2 Feb 2018`

because now only:

`daily from 1 Jan 2018` is supported.

**Comment by rlpowell** [comment]
Done.  Try it out.

**Comment by JSpenced** [comment]
Works as expected on my end. Cheers.
