### ISSUE TITLE
weekly when setting a starting date doesn't work correctly

### ISSUE THREAD

**Issue by JSpenced** [rlpowell/todo-text-stuff#18]
The example shown below it will just run every week from the start date (on the start date aka every Tuesday) and not every week after the start date on Thursday and Friday like it should. The example below it appears that it doesn't recognize the Thursday or Friday at all because it will only actually run once a week on Tuesday? 
```
@2018-12-11 weekly 1; day Thursday, Friday - (B) Test for every Thursday (but runs on Tuesday once a week)
```

Does this make sense? Maybe it isn't supposed to recognize after the `;` but in the examples it says `@2016-03-07 Weekly 2 ; day Thursday - Runs on Thursday every second week starting on the first Thursday after the day specified.` so this should be possible.

**Comment by rlpowell** [comment]
I added some output that should explain what's going on here; try it out, please.
