### ISSUE TITLE
error during running

### ISSUE THREAD

**Issue by uherbst** [rlpowell/todo-text-stuff#2]
uherbst@pculi:~/.todo/action$ todo-txt ice_recur
FAILURE: Something went wrong: uninitialized constant TodoTxt
Did you mean?  Todotxt; /home/uherbst/.todo/action/ice_recur:252:in `block in <main>'
/home/uherbst/.todo/action/ice_recur:251:in `open'
/home/uherbst/.todo/action/ice_recur:251:in `<main>'

Running on debian stable.
What to do to solve this ?
gem install todotxt-rb was done without issues.

**Comment by rlpowell** [comment]
It means that ice_recur isn't seeing the todotxt gem.

This is a scriptlet that should work if the gem is in the right
place:

/usr/bin/env ruby -rtodotxt -e 'puts (File.open("/tmp/todo.txt", "r+") { |todo_fh| TodoTxt::List.from_file(todo_fh) })'

If not, you'll need to figure out how to install the gems in wherever
"/usr/bin/env ruby" expects, which probably means using whatever
"/usr/bin/env which gem" gives.

**Comment by uherbst** [comment]
In Debian there were different ruby libraries with name 'todotxt' - that has confused me (and ice_recur).
This is fixed for me (with manually installing the right one)
