### ISSUE TITLE
Syntax for the repetition genre "last Tuesday"

### ISSUE THREAD

**Issue by daneekadoc** [rlpowell/todo-text-stuff#7]
ice_cube handles the following syntax :

/// every other month on the first monday and last tuesday
schedule.add_recurrence_rule IceCube::Rule.monthly(2).day_of_week(
  :monday => [1],
  :tuesday => [-1]
)

How can that be fed to ice_recur? Can't guess the syntax...

**Comment by rlpowell** [comment]
Done!  Check the new help output to see how.
