### ISSUE TITLE
priority of task is not applied from (D)-(Z)

### ISSUE THREAD

**Issue by rp-karanth** [rlpowell/todo-text-stuff#8]
This is a recurring task list.
 `daily - (A) highly prioritized task @CriticalNow`
 `daily - (B) prioritized task @CriticalNow`
 `daily - (C) some task @CriticalNow`
`daily - (D) another task @CriticalNow`
`daily - (E) another small task @CriticalNow`

After running `todo.sh ice_recur check` this is the result

`(A) 2018-02-28 highly prioritized task @CriticalNow`
`(B) 2018-02-28 prioritized task @CriticalNow`
`(C) 2018-02-28 some task @CriticalNow`
`2018-02-28 (D) another task @CriticalNow`
`2018-02-28 (E) another small task @CriticalNow`

starting from (D) the format changes is this by design?

**Comment by rlpowell** [comment]
Actually that one's not on my end; see https://github.com/tylerdooling/todotxt-rb/pull/1

**Comment by rlpowell** [comment]
In version 1.4, I dropped the todo.txt gem I was using and rolled my own; I believe this fixes this issue.  Please test.
